---
title: Home
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: Picarddamien@outlook.com
description: ''
baseurl: jekyll-web
url: ''
twitter_username: Mr_Pikpik
github_username: MrPikpikLol
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
